### PR TITLE
fixing ninja call

### PR DESCRIPTION
**Pull request by jimon**
fixing #154

### CODE REVIEW

**Comment by jimon** [comment]
meh, but we are missing out a case when output file name is not "build.ninja"

**Comment by den-mentiei** [comment]
It wont show ninja output till its process will terminate?

**Comment by jimon** [comment]
ninja uses ours stdout\stderr directly, no piping involved, at least on
Windows, check it on OSX

**Comment by den-mentiei** [comment]
It works :+1:

**Pull request merged**
